### ISSUE TITLE
Town Overview Scene

### ISSUE THREAD

**Issue by gadse** [gadse/high-moon#23]
Clickable with stubs

Stateless Scene (?)

**Comment by AdrianSchneble** [comment]
Basic functionality (clickable areas/houses) is now possible, but if you click the houses too fast, the scene crashes/resets/reloads for some reason. Further investigation necessary (when it's not 2am).
It also only seems to happen for the purple house (*needs validation!), which doesn't really make sense to me. But oh well ...
